INTEREST_CHOICES = (
    ('animals', 'Animals'),
    ('arts_culture', 'Arts and Culture'),
    ('children', 'Children'),
    ('disaster_relief', 'Disaster Relief'),
    ('education', 'Education'),
    ('environment', 'Environment'),
    ('health', 'Health'),
    ('human_rights', 'Human Rights'),
    ('poverty', 'Poverty'),
    ('seniors', 'Seniors'),
    ('sports', 'Sports'),
    ('women', 'Women'),
    ('other', 'Other'),
)

CAUSE_CHOICES = (
    ('animals', 'Animals'),
    ('arts_culture', 'Arts and Culture'),
    ('children', 'Children'),
    ('disaster_relief', 'Disaster Relief'),
    ('education', 'Education'),
    ('environment', 'Environment'),
    ('health', 'Health'),
    ('human_rights', 'Human Rights'),
    ('poverty', 'Poverty'),
    ('seniors', 'Seniors'),
    ('sports', 'Sports'),
    ('women', 'Women'),
    ('other', 'Other'),
)