# Generated by Django 4.1.7 on 2023-02-24 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('e_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('1', 'ONLINE'), ('2', 'OFFLINE')], default=2, max_length=10)),
                ('start_date', models.DateField(blank=True, verbose_name='startdate(mm/dd/yyyy)')),
                ('end_date', models.DateField(blank=True, verbose_name='enddate(mm/dd/yyyy)')),
                ('nature', models.CharField(max_length=200)),
                ('noofvolunteers', models.IntegerField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
