# Generated by Django 4.1.7 on 2023-02-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='e_desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
