# Generated by Django 4.1.7 on 2023-02-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
