# Generated by Django 4.1.7 on 2023-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_id_baseuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.IntegerField(max_length=12, null=True, unique=True),
        ),
    ]
