# Generated by Django 4.1.7 on 2023-02-24 19:52

import accounts.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_baseuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='volunteer_interests',
            new_name='interests',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='volunteer_bio',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='website',
        ),
        migrations.CreateModel(
            name='NGOModel',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Company Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('bio', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'corporates',
            },
            bases=('accounts.baseuser',),
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
